version: "3.8"
services:
  KRAKEND:
    image: ${KRAKEND_IMAGE}
    networks: 
      - backbone
    volumes:
      - type: bind
        source: ${KRAKEND_DATA}
        target: /etc/krakend/
    environment:
      - FC_ENABLE=1
      - FC_OUT=/etc/krakend/out.json
      - FC_PARTIALS=/etc/krakend/config/partials
      - FC_SETTINGS=/etc/krakend/config/settings/test
      - FC_TEMPLATES=/etc/krakend/config/templates
    ports:
      - '${KRAKEND_HTTP}:8100'
    command: ["run","-dc","krakend.tmpl"]


networks:
  backbone:
    name: chipprbackbone
    external: true