version: '3.2'

services:
  core:
    image: ${HOUND_IMAGE}
    environment:
      - BIND_ADDR=${SH_BIND_ADDR}
      - BIND_PORT=30303
      - PRIVATE_KEY=${SH_PRIVATE_KEY}
      - ESEARCH_HOST='${SH_ESEARCH_HOST}'
      - HOUNDID=${COMPOSE_PROJECT_NAME}
      - CHAIN_FILE='${SH_CHAIN_FILE}'
    ports:
     - "${BIND_PORT}:30303"
    logging:
      driver: gelf
      options:
        tag: ${GELF_TAG}
        gelf-address: "${GELF_ADDRESS}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        
