version: '3.2'

services:
  black_pirl:
    image: ${KT_IMAGE}
    volumes:
      - type: bind
        source: ${KT_ROOT_DIR}
        target: /root
    command: >
               --mordor
               --miner.etherbase ${MINER_ETHERBASE}
               --miner.extradata '${MINER_EXTRADATA}'
               --mine
               --datadir "/root"
               --allow-insecure-unlock
               --rpc
               --rpcapi "${RPC_API}"
               --rpcaddr ${RPC_ADDR}
               --rpcport 8554
               --rpcvhosts="${RPC_VHOSTS}"
               --rpccorsdomain ${RPC_CORS_DOMAIN}
               --shh
               --nousb
               --maxpeers "${MAX_PEERS}"
               --PirlGuard
    ports:
      - '${RPC_PORT}:8554'
      - '${WS_PORT}:8556'
      - '${P2P_PORT}:30303'
    logging:
      driver: gelf
      options:
        tag: ${GELF_TAG}
        gelf-address: "${GELF_ADDR}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  kotti-etherbeat:
    image: ${KT_EB_IMAGE}
  #  volumes:
  #    - type: bind
  #      source: "${KT_EB_DIR}"
  #      target: /root/
    environment:
      - ELASTIC_HOST="${ELASTIC_HOST}"
      - ETH_RPC_ADDR="${ETH_RPC_ADDR}"
      - START_BLOCK="0"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

