version: "3.7"

services:
  grafana:
    image: $GF_IMAGE
    depends_on:
      - prometheus
    ports:
      - "$GF_SERVER_HTTP_PORT:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-etc:/etc/grafana       
    networks:
      - chippr-metrics
    restart: always


  prometheus:
    image: $PROM_IMAGE
    ports:
      - "$PROM_PORT:9090"
    volumes:
      - prometheus-storage:/prometheus
      - $PROM_CONF:/etc/prometheus/prometheus.yml
    networks:
      - chippr-metrics
    restart: always
    
volumes:
  prometheus-storage:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_DATA
      o: bind
  grafana-storage:
    driver: local
    driver_opts:
      type: bind
      device: $GF_DATA
      o: bind
  grafana-etc:
    driver: local
    driver_opts:
      type: bind
      device: $GF_ETC
      o: bind
  
networks:
  chippr-metrics: