version: "3.8"

services:
  GRAFANA:
    image: ${GF_IMAGE}
    volumes:
      - type: bind
        source: ${GF_DATA}
        target: /var/lib/grafana
      - type: bind
        source: ${GF_ETC}
        target: /etc/grafana       
    depends_on:
      - prometheus
    networks:
      - backbone
 
  PROM:
    image: ${PROM_IMAGE}
    volumes:
      - type: bind
        source: ${PROM_DATA}
        target: /prometheus
      - type: bind
        source: ${PROM_CONF}
        target: /etc/prometheus/prometheus.yml
    networks:
      - backbone

networks:
  backbone:
    name: chipprbackbone
    external: true