version: '3.2'

services:
  besu-mainnet:
    image: hyperledger/besu
    volumes:
      - type: bind
        source: "${DATA_PATH}"
        target: /root
    command: >
               --network "${BESU_NETWORK}"
               --identity="${BESU_IDENTITY}"                                                                                                                                                                                                                  --rpc-http-enabled=true
               --rpc-ws-enabled=true
               --rpc-ws-host=0.0.0.0
               --data-path=/root
               --rpc-http-cors-origins=all
               --rpc-http-host=0.0.0.0
               --host-whitelist="${HOST_WHITELIST}"
    ports:
      - '${RPC_PORT}:8545'
      - '${WS_PORT}:8546'
      - '${P2P_PORT}:30303'
    logging:
      driver: gelf
      options:
        tag: ${GELF_TAG}
        gelf-address: "${GELF_ADDRESS}"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

