version: '3.2'

services:
  ZEBRAD:
    image: ${ZEBRAD_IMAGE}
    volumes:
      - type: bind
        source: ${ZEBRAD_DATA}
        target: /etc/zebra
      - type: bind
        source: ${ZEBRAD_CACHE}
        target: /srv/ZEBRAD/.zcash
    command: >     
      ${ZEBRAD_FLAGS}
    ports:
      - '${ZEBRAD_P2P}:8233'