version: '3.2'

services:
  ZEBRAD:
    image: ${ZEBRAD_IMAGE}
    volumes:
      - type: bind
        source: ${ZEBRAD_DATA}
        target: /etc/zebrad
      - type: bind
        source: ${ZEBRAD_CACHE}
        target: /var/cache/zebrad-cache
    command: >     
      ${ZEBRAD_FLAGS}
    ports:
      - '${ZEBRAD_P2P}:8232'