version: '3.2'
services:
  mina:
    image: ${MINA_IMAGE}
    volumes:
      - type: bind
        source: "${MINA_KEY_DIR}"
        target: /keys/
      - type: bind
        source: "${MINA_CONFIG_DIR}"
        target: /root/.mina-config/
      - type: bind
        source: "${MINA_WORK_DIR}"
        target: /var/lib/coda/
    environment:
      CODA_PRIVKEY_PASS: "${MINA_PRIVKEY_PASS}"
    command: >
             daemon
             --insecure-rest-server 
             --file-log-level "${MINA_FILE_LOG_LEVEL}"
             --log-level "${MINA_LOGLEVEL}" 
             --peer-list-url "${MINA_PEER_LIST_URL}"
             --external-ip "${MINA_EXT_IP}"
    ports:
      - "${MINA_P2P}:8302"
      - "${MINA_API}:3085"
   # logging:
   #   driver: gelf
   #   options:
   #     tag: ${MINA_TAG}
   #     gelf-address: "${GELF_ADDRESS}"
