version: '3.2'
services:
  mina:
    image: ${MINA_IMAGE}
    volumes:
      - type: bind
        source: "${MINA_KEY_DIR}"
        target: /keys/
      - type: bind
        source: "${MINA_CONFIG_DIR}"
        target: /root/.mina-config/
    environment:
      CODA_PRIVKEY_PASS: "${MINA_PRIVKEY_PASS}"
    command: >
             daemon
             --block-producer-key /keys/my-wallet
             --insecure-rest-server 
             --file-log-level "${MINA_FILE_LOG_LEVEL}"
             --log-level "${MINA_LOGLEVEL}" 
             --peer-list-url "${MINA_PEER_LIST_URL}"
             --run-snark-worker "${MINA_PUBLIC_KEY}" 
             --snark-worker-fee "${MINA_SNARK_FEE}"
    ports:
      - "${MINA_P2P}:8302"
   # logging:
   #   driver: gelf
   #   options:
   #     tag: ${MINA_TAG}
   #     gelf-address: "${GELF_ADDRESS}"
