version: '3.8'
services:
  REDIS:
    image: ${VECTOR_IMAGE}
    environment:
      - REDISEARCH_ARGS=CONCURRENT_WRITE_MODE
    volumes:
      - type: bind
        source: ${VECTOR_DATA}
        target: /var/lib/redis
      - type: volume
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 2s
      timeout: 1m30s
      retries: 5
      start_period: 5s