version: "3.8"

services:
  IPFS:
    image: ${IPFS_IMAGE}
    volumes:
      - type: bind
        source: "${IPFS_EXPORT_DIR}"
        target: /export/
      - type: bind
        source: "${IPFS_DATA_DIR}"
        target: /data/ipfs
    networks:
      - backbone

networks:
  backbone:
    name: chipprbackbone
    external: true

