version: "3.2"
services:
  ipfs:
    image: ${IPFS_IMAGE}
    volumes:
      - type: bind
        source: "${IPFS_EXPORT_DIR}"
        target: /export/
      - type: bind
        source: "${IPFS_DATA_DIR}"
        target: /data/ipfs
    restart: always
    ports:
      - "${IPFS_API_PORT}:5001"
      - "${IPFS_UI_PORT}:4001"
      - "${IPFS_P2P_PORT}:8080"
#    logging:
#      driver: gelf
#      options:
#        tag: ${IPFS_TAG}
#        gelf-address: "${GELF_ADDRESS}"

