version: '3.8'

services:
  COREGETH:
    image: ${IMAGE}
    networks:
      - backbone
    volumes:
      - type: bind 
        source: ${DATA}
        target: /root
    command: [ ${GETH_FLAGS} ]

networks:
  backbone:
    name: chipprbackbone
    external: true
