version: '3.2'

services:
  lightwalletd:
    image: ${LWD_IMAGE}
    entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    volumes:
        - "${PWD}:/srv/lightwalletd"
        - lightwalletd_cache:/var/lib/lightwalletd

    command: 
      - --grpc-bind-addr=0.0.0.0:8000
      - --http-bind-addr=0.0.0.0:8100
      - --log-file=/dev/stdout
      - --log-level=7
      - --rpchost=${LWD_ZEBRAHOST}
      - --rpcport=${LWD_ZEBRAPORT}
      - --no-tls-very-insecure
      - --zcash-conf-path=/srv/lightwalletd/zcash.conf
      #     --tls-cert=/var/lib/lightwalletd/cert.pem
#     --tls-key=/var/lib/lightwalletd/key.pem 
    ports:
      - '${LWD_GRPC_PORT}:8000'
      - '${LWD_HTTP_PORT}:8100'      
    restart: always
    networks:
      - backbone

volumes:
  lightwalletd_cache: 

networks:
  backbone:
    name: chippr-backbone
    external: true
