version: '3.8'

services:
  lightwalletd:
    image: ${LWD_IMAGE}
    networks: 
      - backbone
    #entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    volumes:
        - type: bind
          source: ${PWD}
          target: /srv/lightwalletd
        - type: volume
          source: lightwalletd_cache
          target: /var/lib/lightwalletd
    command: 
      - --grpc-bind-addr=0.0.0.0:8000
      - --http-bind-addr=0.0.0.0:8100
      - --log-file=/dev/stdout
      - --log-level=7
      - --rpchost=${LWD_ZEBRAHOST}
      - --rpcport=${LWD_ZEBRAPORT}
      - --no-tls-very-insecure
      - --zcash-conf-path=/srv/lightwalletd/zcash.conf
      #     --tls-cert=/var/lib/lightwalletd/cert.pem
#     --tls-key=/var/lib/lightwalletd/key.pem 
    ports:
      - '${LWD_GRPC_PORT}:8000'
      - '${LWD_HTTP_PORT}:8100'

networks:
  backbone:
    name: chipprbackbone
    external: true

volumes:
  lightwalletd_cache: 

