version: '3.2'

services:
  core:
    image: ${BRIDGETTE_IMAGE}
    volumes:
      - type: bind
        source: "${CORE_SRC}"
        target: /vault/
    environment:
      - WEB3_URL=${CORE_WEB3_URL}
      - LOG_LEVEL=${CORE_LOGLEVEL}
      - DISCORD_TOKEN=${CORE_DISCORD_TOKEN}
      - BRIDGETTE_ADDRESS=${CORE_BRIDGETTE_ADDR}
      - BRIDGETTE_PW=${CORE_BRIDGETTE_PW}
      - KOTTI_NODE=${CORE_KOTTI_NODE}
      - TICKERFEED=${CORE_TICKERFEED}
      - VAULT_KEY=${CORE_VAULT_KEY}
      - VAULT_CERT=${CORE_VAULT_CERT}
      - ESEARCH_HOST=${DB_ESEARCH_HOST}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        
