version: "3.7"

services:
  grafana:
    image: $GF_IMAGE
    depends_on:
      - prometheus
    ports:
      - "$GF_SERVER_HTTP_PORT:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-etc:/etc/grafana       
    networks:
      - zcashd-metrics
    restart: always


  prometheus:
    image: $PROM_IMAGE
    container_name: zcashd-prometheus
    ports:
      - "$PROM_PORT:9090"
    volumes:
      - prometheus-storage:/prometheus
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - zcashd-metrics
    restart: always
    extra_hosts:
      - "host.docker.internal:$ZCASH_IP"

volumes:
  prometheus-storage:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_DATA
      o: bind
  prometheus-config:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_CONF
      o: bind
  grafana-storage:
    driver: local
    driver_opts:
      type: bind
      device: $GF_DATA
      o: bind
  grafana-etc:
    driver: local
    driver_opts:
      type: bind
      device: $GF_ETC
      o: bind
  
networks:
  zcashd-metrics: