version: "3.7"

services:
  grafana:
    image: $GF_IMAGE
    depends_on:
      - prometheus
    ports:
      - "$GF_SERVER_HTTP_PORT:3030"
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
      - type: bind
        source: grafana-etc
        target: /etc/grafana       
    networks:
      - zcashd-metrics
    restart: always


  prometheus:
    image: PROM_IMAGE
    container_name: zcashd-prometheus
    ports:
      - "$PROM_PORT:9090"
    volumes:
      - type: volume
        source: prometheus-storage
        target: /prometheus
      - type: bind
        source: prometheus-config
        target: /etc/prometheus/prometheus.yml
        read_only: true
    networks:
      - zcashd-metrics
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus-storage:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_DATA
      o: bind
  prometheus-config:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_CONF
      o: bind
  grafana-data:
    driver: local
    driver_opts:
      type: bind
      device: $GF_DATA
      o: bind
  grafana-etc:
    driver: local
    driver_opts:
      type: bind
      device: $GF_ETC
      o: bind
  
networks:
  zcashd-metrics: