version: '3.8'
services:
  trezor:
    image: ${TZ_IMAGE}
    networks:
      - backbone
    ports:
      - "${TZ_PORT}:8080"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3        

networks:
  backbone:
    name: chipprbackbone
    external: true