version: '3.2'
services:
  trezor:
    image: ${TZ_IMAGE}
    ports:
      - "${TZ_PORT}:8000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3        

