version: '3.7'
services:

  web3Signer:
    image: $WEB3SIGNER_IMAGE
    ports:
      - "$WEB3SIGNER_HTTP_LISTEN_PORT:$WEB3SIGNER_HTTP_LISTEN_PORT"
      - "$WEB3SIGNER_METRICS_PORT:$WEB3SIGNER_METRICS_PORT"
    command:
      -  web3signer eth1
    