version: '3.8'
services:
  WEB3SIGNER:
    image: ${WEB3SIGNER_IMAGE}
    volumes:
      - type: bind
        source: ${WEB3SIGNER_DATA_PATH}
        target: /opt/web3Signer
    command:
      ${SIGNER_FLAGS}