---
version: '2'

services:
  zcashd:
    image: $ZCASHD_IMAGE
    volumes:
      - zcashd_lite_data:/srv/zcashd/.zcash
      - zcashd_lite_data:/srv/zcashd/.zcash-params
    command:
      - --prune=$ZCASHD_PRUNE_SIZE 
    mem_limit: 15G
    ports:
      - "0.0.0.0:$ZCASHD_P2P:8232"
      - "9050:9050"
    restart: always

volumes:
  zcashd_lite_data:
    driver: local
    driver_opts:
      type: bind
      device: $ZCASHD_DATA
      o: bind
