---
version: '3'

services:
  zcashd:
    image: $ZCASHD_IMAGE
    volumes:
      - zcashd_data:/srv/zcashd/.zcash
      - zcashd_data:/srv/zcashd/.zcash-params
    environment:
      - ZCASHD_EXPERIMENTALFEATURES=$ZCASHD_EXPERIMENTALFEATURES
      - ZCASHD_INSIGHTEXPLORER=$ZCASHD_INSIGHTEXPLORER
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_PROMETHEUSPORT=$ZCASHD_PROMETHEUSPORT
      - ZCASHD_TXINDEX=$ZCASHD_TXINDEX
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
    command:
      - --reindex=$ZCASHD_REINDEX
      - --lightwalletd=$ZCASHD_LIGHTWALLETD   
    ports:
      - "$ZCASHD_P2P:8233"
      - "$ZCASHD_RPC:8232"
      - "$ZCASHD_PROMETHEUSPORT:$ZCASHD_PROMETHEUSPORT"

volumes:
  zcashd_data:
    driver: local
    driver_opts:
      type: bind
      device: $ZCASHD_DATA
      o: bind
