---
version: '2'

services:
  zcashd:
    image: $ZCASHD_IMAGE
    volumes:
      - zcashd_data:/srv/zcashd/.zcash
      - zcashd_data:/srv/zcashd/.zcash-params
    environment:
      - ZCASHD_EXPERIMENTALFEATURES=$ZCASHD_EXPERIMENTALFEATURES
      - ZCASHD_INSIGHTEXPLORER=$ZCASHD_INSIGHTEXPLORER
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_PROMETHEUSPORT=$ZCASHD_PROMETHEUSPORT
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_TXINDEX=$ZCASHD_TXINDEX
      - ZCASHD_METRICSIP=$ZCASHD_METRICSIP
    mem_limit: 15G
    ports:
      - "0.0.0.0:$ZCASHD_P2P:8233"
      - "$ZCASHD_PROMETHEUSPORT:$ZCASHD_PROMETHEUSPORT"
    restart: always

volumes:
  zcashd_data:
    driver: local
    driver_opts:
      type: bind
      device: $ZCASHD_DATA
      o: bind
