---
version: '2'

services:
  lightwalletd:
    image: $LWD_IMAGE
    #entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    command:
      - --grpc-bind-addr=0.0.0.0:$LWD_GRPC_PORT
      - --http-bind-addr=0.0.0.0:$LWD_HTTP_PORT
      - --zcash-conf-path=/var/lib/lightwalletd/zcash.conf
      - --log-file=/dev/stdout
      - --log-level=7
      - --no-tls-very-insecure
#      - --tls-cert=/var/lib/lightwalletd/cert.pem
#      - --tls-key=/var/lib/lightwalletd/key.pem 
    ports:
      - "0.0.0.0:$LWD_GRPC_PORT:$LWD_GRPC_PORT"
      - "0.0.0.0:$LWD_HTTP_PORT:$LWD_HTTP_PORT"      
    volumes:
      - lightwalletd_cache:/srv/lightwalletd
      - lightwalletd_cache:/var/lib/lightwalletd
    depends_on: 
      - loki
      - zcashd
    restart: always
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  zcashd:
    image: $ZEC_IMAGE
    volumes:
      - zcashd_data:/srv/zcashd/.zcash
      - zcashd_data:/srv/zcashd/.zcash-params
#    command:
#      - --exportdir=/srv/zcashd/.zcash 
    mem_limit: 15G
    ports:
      - "0.0.0.0:38232:38232"
      - "9050:9050"
    restart: always
    depends_on:
      - loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  zcashd_exporter:
    image: $ZEC_EXPORTER_IMAGE
    environment:
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
    command:
      - --rpc.host=zcashd
      - --rpc.port=$ZCASHD_RPCPORT
      - --rpc.user=$ZCASHD_RPCUSER
      - --rpc.password=$ZCASHD_RPCPASSWORD
    ports:
      - "127.0.0.1:9100:9100"
    restart: always
    depends_on:
      - loki
      - zcashd
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  grafana:
    image: $GF_IMAGE
    entrypoint:
      - bash
      - -c
      - grafana-cli plugins install grafana-piechart-panel && /run.sh
    ports:
      - "0.0.0.0:3000:3000"
    volumes:
      - grafana_data:/etc/grafana
    restart: always
    depends_on:
      - loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  prometheus:
    image: $PROM_IMAGE
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./docker/prometheus/config.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    mem_limit: 2G
    restart: always
    depends_on:
      - loki
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

  loki:
    image: $LOKI_IMAGE
    ports:
      - "127.0.0.1:3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'

volumes:
  zcashd_data:
    driver: local
    driver_opts:
      type: bind
      device: $ZCASHD_DATA
      o: bind
  prometheus_data:
    driver: local
    driver_opts:
      type: bind
      device: $PROM_DATA
      o: bind
  grafana_data:
    driver: local
    driver_opts:
      type: bind
      device: $GF_DATA
      o: bind
  lightwalletd_cache:
    driver: local
    driver_opts: 
      type: bind
      device: $LWD_DATA
      o: bind
